FROM node:lts-alpine
ENV PORT 3000

WORKDIR /usr/src/app

# Installing dependencies
RUN set -ex && \
    apk add --no-cache --virtual git
RUN npm install --global --unsafe-perm ts-node
COPY package.json yarn.lock .npmrc ./
RUN yarn install

# Copying source files
COPY . .

# Running the app
EXPOSE 3000
CMD ["yarn", "dev"]
